name: Deploy

on:
  push: {branches: main}

env:
  NODE_VERSION: 16

jobs:
  release:
    runs-on: ubuntu-latest
    if:
      github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&
        github.repository == 'nex3/cohost-backloggd'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm install
    - run: npm run -- build --base-href /cohost-backloggd/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
      with:
        personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: nex3/nex3.github.io
        publish_dir: ./dist
        destination_dir: cohost-backloggd
        publish_branch: main
        allow_empty_commit: true

